GPU available: True, used: True
TPU available: False, using: 0 TPU cores
CUDA_VISIBLE_DEVICES: [0]
Set SLURM handle signals.
/cluster/raid/home/zhivar.sourati/anaconda3/envs/explagraphgen/lib/python3.8/site-packages/transformers/generation_utils.py:760: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  beam_id = beam_token_id // vocab_size
Traceback (most recent call last):
  File "src/train_graph_gen_contrastive.py", line 472, in <module>
    main(args)
  File "src/train_graph_gen_contrastive.py", line 461, in main
    trainer.test(model)
  File "/cluster/raid/home/zhivar.sourati/anaconda3/envs/explagraphgen/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in test
    results = self.__test_given_model(model, test_dataloaders)
  File "/cluster/raid/home/zhivar.sourati/anaconda3/envs/explagraphgen/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1335, in __test_given_model
    model.setup('test')
  File "/cluster/raid/home/zhivar.sourati/ExplagraphGen/src/lightning_base.py", line 170, in setup
    self.dataset_size = len(self.val_dataloader().dataset)
  File "src/train_graph_gen_contrastive.py", line 324, in test_dataloader
    return self.get_dataloader("val", batch_size=self.hparams.eval_batch_size)
  File "src/train_graph_gen_contrastive.py", line 281, in get_dataloader
    dataset = self.get_dataset(type_path)
  File "src/train_graph_gen_contrastive.py", line 271, in get_dataset
    dataset = self.dataset_class(
  File "/cluster/raid/home/zhivar.sourati/ExplagraphGen/src/utils_contrastive.py", line 131, in __init__
    self.src_lens = self.get_char_lens(self.src_file)
  File "/cluster/raid/home/zhivar.sourati/ExplagraphGen/src/utils_contrastive.py", line 150, in get_char_lens
    return [len(x) for x in Path(data_file).open().readlines()]
  File "/cluster/raid/home/zhivar.sourati/anaconda3/envs/explagraphgen/lib/python3.8/pathlib.py", line 1218, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/cluster/raid/home/zhivar.sourati/anaconda3/envs/explagraphgen/lib/python3.8/pathlib.py", line 1074, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'contrastive_data/test.source'
